apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dkkzodofv-python
  janus-idp.io/tekton: dkkzodofv-python
  backstage.io/kubernetes-id: dkkzodofv-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dkkzodofv-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
